### ISSUE TITLE
service unable to read runtime configuration file

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#84]
I think that the dripline environment set up by the helm chart can't read my authentications file.

First, I make a rabbitmq-authentications-secret.yaml file.
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-authentications-secret
type: Opaque
stringData:
  authentications.json: |-
    {
      "amqp": {
        "broker": "rabbitmq-app.default.svc.cluster.local"
        "username": "dripline"
        "password": "dripline"
      }
    }
```
I then apply the secret using kubectl apply -f rabbitmq-authentications-secret.yaml. If I do a kubectl get secrets, I see the secret has been made.

> rabbitmq-authentications-secret      Opaque                                1      36m

https://github.com/driplineorg/dripline-python/blob/develop/chart/values.yaml#L8

I then replace line 8 of the values file with the secrets name, as shown below.
```

replicaCount: 1

rabbitmqSecretName: "rabbitmq-authentications-secret"

configFileData: ~
```
I then install the helm chart, but the container has trouble starting up. If I look into the container, I see the following error in bold.
```
2020-04-07 21:36:30 [DEBUG] (tid 140057941276480) dexed_factory.hh(208): Registered a indexed_factory for class 999 at 0x7f61c6a7d9b0, indexed_factory #24 for 0x5651d70f0d10
2020-04-07 21:36:30 [DEBUG] (tid 140057941276480) i/application.cc(109): first configuration stage
2020-04-07 21:36:30 [DEBUG] (tid 140057941276480) i/application.cc(117): second configuration stage
**2020-04-07 21:36:30 [DEBUG] (tid 140057941276480) i/application.cc(121): Loading config file <"/etc/config/config_file.yaml"> from filename </etc/config/config_file.yaml>
version should be: 0.0.0
Traceback (most recent call last):
  File "/usr/local/bin/dl-serve", line 103, in <module>
    the_main.execute(sys.argv)
RuntimeError: [application] configuration file must consist of an object/node**
2020-04-07 21:36:30 [DEBUG] (tid 140057941276480) dexed_factory.hh(220): Removing indexed_factory for class 999 from 0x5651d70f0d10
```

Any ideas about what might have gone wrong?

**Comment by laroque** [comment]
Is the `configFileData` field still the default (null) as you pasted above? That field is required, it should be the content of the runtime config file used by dl-serve (an actual yaml data structure, the chart will encode it to a string when it creates the text file in the config map)

**Comment by raphaelcervantes** [comment]
Here is my

**Comment by laroque** [comment]
The chart isn't really documented, I'd intended to add a "second-mesh" to the controls guide that is the same as the first, but does it using the chart; but it isn't something I've had a chance to do yet.

**Comment by laroque** [comment]
remove the pipe (`|`) when you define `configFileData`, that causes everything after it to be a string. That was the pattern from the first take chart we used in site-atlas, but this one accepts a native yaml object.

**Comment by laroque** [comment]
@raphaelcervantes I've renamed this issue. Please update if the above resolved your issue.

**Comment by raphaelcervantes** [comment]
@laroque I haven't solved it.

I tried to adopt the[ tutorial example ](https://driplineorg.github.io/controls-guide/develop/guides/first-mesh.html)into a kubernetes config file

```
raphaelc@host:~/dir$ cat releases/dripline-python/kv-store-values.yaml 
replicaCount: 1

configFileData: 
  name: my_store
  module: Service
  auth_file: /root/authentications.json
  endpoints:
        - name: peaches
          module: KeyValueStore
          calibration: '2*{}'
          initial_value: 0.75
          log_interval: 10
          get_on_set: True
          log_on_set: True
        - name: chips
          module: KeyValueStore
          calibration: 'times3({})'
          initial_value: 1.75
        - name: waffles
          module: KeyValueStore
          #log_interval: 30
          #log_on_set: True
          calibration: '1.*{}'
          initial_value: 4.00 
```
But now I get this error

> 
> 2020-04-07 22:33:41 [DEBUG] (tid 140231193990976) dexed_factory.hh(208): Registered a indexed_factory for class 999 at 0x7f8a1d5279b0, indexed_factory #24 for 0x5571c370a860
> 2020-04-07 22:33:42 [DEBUG] (tid 140231193990976) i/application.cc(109): first configuration stage
> 2020-04-07 22:33:42 [DEBUG] (tid 140231193990976) i/application.cc(117): second configuration stage
> 2020-04-07 22:33:42 [DEBUG] (tid 140231193990976) i/application.cc(121): Loading config file <"/etc/config/config_file.yaml"> from filename </etc/config/config_file.yaml>
> 2020-04-07 22:33:42 [ERROR] (tid 140231193990976) i/application.cc(94): Unable to parse remaining arguments: Cannot parse an option with the nonoption_parser: -v
> Unable to parse remaining arguments due to parse error or unknown option: Cannot parse an option with the nonoption_parser: -v
> Run with --help for more information.
> version should be: 0.0.0
> 2020-04-07 22:33:42 [DEBUG] (tid 140231193990976) dexed_factory.hh(220): Removing indexed_factory for class 999 from 0x5571c370a860

**Comment by raphaelcervantes** [comment]
Is the `runtime-config` keyword needed somewhere?

**Comment by laroque** [comment]
The configuration you have needs to be in a top-level key named `runtime-config`, just as in the [tutorial](https://driplineorg.github.io/controls-guide/develop/guides/first-mesh.html#id4). The file could have other top-level fields, these are planned but I don't know that any are supported yet.

**Comment by raphaelcervantes** [comment]
I have changed my config file to the following, but still get the same parsing error. I added the `runtime-config` field on top, and I also changed auth_file from `/root/authentications.json` to `/etc/config/authentications.json`

replicaCount: 1

configFileData: 
  runtime-config:
    name: my_store
    module: Service
    auth_file: /etc/config/authentications.json
    endpoints:
      - name: peaches
        module: KeyValueStore
        calibration: '2*{}'
        initial_value: 0.75
        log_interval: 10
        get_on_set: True
        log_on_set: True
      - name: chips
        module: KeyValueStore
        calibration: 'times3({})'
        initial_value: 1.75
      - name: waffles
        module: KeyValueStore
        #log_interval: 30
        #log_on_set: True
        calibration: '1.*{}'
        initial_value: 4.00

**Comment by laroque** [comment]
Oh, I don't think I read carefully (though the above was an issue also).

Did you [re]build the dripline-python container image? You need to be running 4.3 to use the `-v` flag to `dl-serve`, maybe actually 4.3.1 (HEAD of master right now). Develop should also work, but builds from before that won't.

**Comment by raphaelcervantes** [comment]
I have pulled dripline 4.3.1 image. 
It works better now, but now my kv-store example can't read my my authentications file.
I'm pasting the logs below

```
2020-04-07 23:35:04 [ PROG] i/application.cc(128): Final configuration:

{
    dripline : 
    {
        alerts-exchange : alerts
        broker : rabbitmq-app
        heartbeat-interval-s : 60
        heartbeat-routing-key : heartbeat
        loop-timeout-ms : 1000
        max-payload-size : 10000
        message-wait-ms : 1000
        requests-exchange : requests
    }

    runtime-config : 
    {
        auth_file : /etc/config/authentications.json
        endpoints : 
        [
            
            {
                calibration : 2*{}
                get_on_set : true
                initial_value : 0.750000
                log_interval : 10
                log_on_set : true
                module : KeyValueStore
                name : peaches
            }

            
            {
                calibration : times3({})
                initial_value : 1.750000
                module : KeyValueStore
                name : chips
            }

            
            {
                calibration : 1.*{}
                initial_value : 4
                module : KeyValueStore
                name : waffles
            }

        ]

        module : Service
        name : my_store
    }

}

2020-04-07 23:35:04 [ PROG] i/application.cc(129): Ordered args:

[
]

2020-04-07T23:35:04[INFO    ] dripline(86) -> python got a master config:
{'dripline': {'alerts-exchange': 'alerts', 'broker': 'rabbitmq-app', 'heartbeat-interval-s': 60, 'heartbeat-routing-key': 'heartbeat', 'loop-timeout-ms': 1000, 'max-payload-size': 10000, 'message-wait-ms': 1000, 'requests-exchange': 'requests'}, 'runtime-config': {'auth_file': '/etc/config/authentications.json', 'endpoints': [{'calibration': '2*{}', 'get_on_set': True, 'initial_value': 0.75, 'log_interval': 10, 'log_on_set': True, 'module': 'KeyValueStore', 'name': 'peaches'}, {'calibration': 'times3({})', 'initial_value': 1.75, 'module': 'KeyValueStore', 'name': 'chips'}, {'calibration': '1.*{}', 'initial_value': 4, 'module': 'KeyValueStore', 'name': 'waffles'}], 'module': 'Service', 'name': 'my_store'}}
2020-04-07 23:35:04 [ERROR] uthentication.cc(53): File either doesn't exist (0) or isn't a regular file (0)
2020-04-07T23:35:04[ERROR   ] dripline(75) -> got an error...
2020-04-07T23:35:04[ERROR   ] dripline(76) -> traceback was:
Traceback (most recent call last):
  File "/usr/local/bin/dl-serve", line 73, in run
    self._run(the_app)
  File "/usr/local/bin/dl-serve", line 96, in _run
    the_service = self.create_object( run_config )
  File "/usr/local/bin/dl-serve", line 67, in create_object
    the_object = module( **a_config )
_dripline.core.DriplineError: Authentication file </etc/config/authentications.json> could not be loaded

```

**Comment by laroque** [comment]
Do you have something mounted to `/etc/config/authentications.json`?

The chart template mounts the secret to `/etc/rabbitmq-secret` (https://github.com/driplineorg/dripline-python/blob/63a3cb0aad6198cd4ebfc892e74485c22583f2f7/chart/templates/dripline-python-deployment.yaml#L38). So you should be able to pass set the authentication sfile path to `/etc/rabbitmq-secret/authentications.json` if you're using the secret. If you're mounting your own file elsewhere you'll need to use whatever path you configured.

**Comment by raphaelcervantes** [comment]
Meanwhile, my hardware configuration is pasted below. It seems to connect to my rabbitmq server, but now I run into an error     
```
the_endpoints = run_config.pop("endpoints", [])                                                                  
AttributeError: 'NoneType' object has no attribute 'pop'    
```
Here is the configuration file
```
raphaelc@host:~/orpheus_site_atlas$ cat releases/dripline-python/na-simple-values.yaml 
replicaCount: 1

#image:
    #repository: dragonfly-extended
    #tag: beta
    #pullPolicy: IfNotPresent


configFileData: 
    name: na
    module: Service
    broker: rabbit_broker
    endpoints:
      - name: na_interface
        module: EthernetSCPIService
        socket_info: ("secret ip",5025)
        socket_timeout: 3
        cmd_at_reconnect:
          - 
          - "SYST:ERRor?"  
          - "*OPC?"
        reconnect_test: '+1'
        command_terminator: "\n"
        response_terminator: "\n"
        endpoints:
          - &basic_spime
            name: na_start_freq         
            module: SimpleSCPIEntity
            base_str: :SENSe:FREQuency:STARt
            calibration: "{}"
          - <<: *basic_spime
            name: na_stop_freq
            base_str: :SENSe:FREQuency:STOP
          - <<: *basic_spime
            name: na_center_freq
            base_str: :SENSe:FREQuency:CENTer
          - <<: *basic_spime
            name: na_freq_span
            base_str: :SENSe:FREQuency:SPAN
```
And here is the log output. 

> 2020-04-07 23:30:58 [ PROG] i/application.cc(128): Final configuration:
> 
> {
>     broker : rabbit_broker
>     dripline : 
>     {
>         alerts-exchange : alerts
>         broker : rabbitmq-app
>         heartbeat-interval-s : 60
>         heartbeat-routing-key : heartbeat
>         loop-timeout-ms : 1000
>         max-payload-size : 10000
>         message-wait-ms : 1000
>         requests-exchange : requests
>     }
> 
>     endpoints : 
>     [
>         
>         {
>             cmd_at_reconnect : 
>             [
>                 
>                 SYST:ERRor?
>                 *OPC?
>             ]
> 
>             command_terminator : 
> 
>             endpoints : 
>             [
>                 
>                 {
>                     base_str : :SENSe:FREQuency:STARt
>                     calibration : {}
>                     module : SimpleSCPIEntity
>                     name : na_start_freq
>                 }
> 
>                 
>                 {
>                     base_str : :SENSe:FREQuency:STOP
>                     calibration : {}
>                     module : SimpleSCPIEntity
>                     name : na_stop_freq
>                 }
> 
>                 
>                 {
>                     base_str : :SENSe:FREQuency:CENTer
>                     calibration : {}
>                     module : SimpleSCPIEntity
>                     name : na_center_freq
>                 }
> 
>                 
>                 {
>                     base_str : :SENSe:FREQuency:SPAN
>                     calibration : {}
>                     module : SimpleSCPIEntity
>                     name : na_freq_span
>                 }
> 
>             ]
> 
>             module : EthernetSCPIService
>             name : na_interface
>             reconnect_test : 1
>             response_terminator : 
> 
>             socket_info : ("192.168.25.7",5025)
>             socket_timeout : 3
>         }
> 
>     ]
> 
>     module : Service
>     name : na
> }
> 
> 2020-04-07 23:30:58 [ PROG] i/application.cc(129): Ordered args:
> 
> [
> ]
> 
> 2020-04-07T23:30:58[INFO    ] dripline(86) -> python got a master config:
> {'broker': 'rabbit_broker', 'dripline': {'alerts-exchange': 'alerts', 'broker': 'rabbitmq-app', 'heartbeat-interval-s': 60, 'heartbeat-routing-key': 'heartbeat', 'loop-timeout-ms': 1000, 'max-payload-size': 10000, 'message-wait-ms': 1000, 'requests-exchange': 'requests'}, 'endpoints': [{'cmd_at_reconnect': [None, 'SYST:ERRor?', '*OPC?'], 'command_terminator': '\n', 'endpoints': [{'base_str': ':SENSe:FREQuency:STARt', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_start_freq'}, {'base_str': ':SENSe:FREQuency:STOP', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_stop_freq'}, {'base_str': ':SENSe:FREQuency:CENTer', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_center_freq'}, {'base_str': ':SENSe:FREQuency:SPAN', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_freq_span'}], 'module': 'EthernetSCPIService', 'name': 'na_interface', 'reconnect_test': 1, 'response_terminator': '\n', 'socket_info': '("192.168.25.7",5025)', 'socket_timeout': 3}], 'module': 'Service', 'name': 'na'}    
> 2020-04-07T23:30:58[ERROR   ] dripline(75) -> got an error...
> 2020-04-07T23:30:58[ERROR   ] dripline(76) -> traceback was:
> Traceback (most recent call last):                                                                                   
>   File "/usr/local/bin/dl-serve", line 73, in run                                                                    
>     self._run(the_app)                                                                                               
>   File "/usr/local/bin/dl-serve", line 91, in _run                                                                   
>     the_endpoints = run_config.pop("endpoints", [])                                                                  
> AttributeError: 'NoneType' object has no attribute 'pop'
