### ISSUE TITLE
EthernetSCPIService reconnection test fails

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#86]
I am trying to use the `EthernetSCPIService` module to connect to a network analyzer. The connection is established, but the dripline instance seems to crash because the reconnection test failed. Any idea why this is the case? 

I am using v4.3.1-amd64. I am pasting my configuration file and the log output with the error. My guess is that the outputs of `cmd_at_reconnect` and `reconnect_test` aren't identical and therefore throws an error. @nsoblath's guess is that `reconnect_test `here should be `'+1'` instead of `'1'`

```
  runtime-config:
    name: na
    module: EthernetSCPIService
    broker: rabbit_broker
    socket_info: ("192.168.25.7",5025)
    socket_timeout: 3
    cmd_at_reconnect:
      - 
      - "SYST:ERRor?"  
      - "*OPC?"
    reconnect_test: '+1'
    command_terminator: "\n"
    response_terminator: "\n"
    endpoints:
      - &basic_spime
        name: na_start_freq         
        module: SimpleSCPIEntity
        base_str: :SENSe:FREQuency:STARt
        calibration: "{}"
      - <<: *basic_spime
        name: na_stop_freq
        base_str: :SENSe:FREQuency:STOP
      - <<: *basic_spime
        name: na_center_freq
        base_str: :SENSe:FREQuency:CENTer
      - <<: *basic_spime
        name: na_freq_span
        base_str: :SENSe:FREQuency:SPAN
```
>2020-04-08T18:05:37[INFO    ] dripline.implementations.ethernet_scpi_service(86) -> Ethernet socket ('192.168.25.7', 5025) established
>2020-04-08T18:05:40[WARNING ] dripline.implementations.ethernet_scpi_service(194) -> socket.timeout condition met; received:
> 2020-04-08T18:05:40[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: 'SYST:ERRor?\n' -> '+0,"No error"'
> 2020-04-08T18:05:40[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '*OPC?\n' -> '+1'
> 2020-04-08T18:05:40[WARNING ] dripline.implementations.ethernet_scpi_service(103) -> Failed connection test.  Response was ['+0,"No error"', '+1']
> 2020-04-08T18:05:40[ERROR   ] dripline(75) -> got an error...
> 2020-04-08T18:05:40[ERROR   ] dripline(76) -> traceback was:
> Traceback (most recent call last):
>   File "/usr/local/bin/dl-serve", line 73, in run
>     self._run(the_app)
>   File "/usr/local/bin/dl-serve", line 96, in _run
>     the_service = self.create_object( run_config )
>   File "/usr/local/bin/dl-serve", line 67, in create_object
>     the_object = module( **a_config )
>   File "/usr/local/lib/python3.7/site-packages/dripline/implementations/ethernet_scpi_service.py", line 72, in __init__
>     self._reconnect()
>   File "/usr/local/lib/python3.7/site-packages/dripline/implementations/ethernet_scpi_service.py", line 105, in _reconnect
>     raise ThrowReply('resource_error_connection', "Failed connection test.")
> dripline.core.throw_reply.ThrowReply: Failed connection test.
