### ISSUE TITLE
dripline won't connect to my network analyzer (again)

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#99]
Unfortunately, it looks like dripline is having trouble connecting to my network analyzer. I confirmed that I can connect with telnet+scpi.
 I'm now using dripline-python v4.4.2. It looks like the reconnect_test is being interpreted correctly, so I don't understand.

### Telnet connection
```
raphaelc@nlwymmd:~$ telnet <redacted-ip> 5024
Trying <redacted-ip>...
Connected to <redacted-ip>.
Escape character is '^]'.
SCPI> *IDN?
Agilent Technologies,E5063A,MY54100104,A.03.00
SCPI>
```
### NA configuration file
```
raphaelc@nlwymmd:~/orpheus_site_atlas/releases/dripline-python$ cat na-values.yaml
replicaCount: 1

#image:
  #repository: dragonfly-extended
  #tag: beta
  #pullPolicy: IfNotPresent

configFileData:
  runtime-config:
    name: na
    module: EthernetSCPIService
    auth_file: /etc/rabbitmq-secret/authentications.json
    socket_info: ("192.168.25.7",5025)
    socket_timeout: 3
    cmd_at_reconnect:
      -
      - "SYST:ERRor?"
      - "*OPC?"
    reconnect_test: "'+1'"
    command_terminator: "\n"
    response_terminator: "\n"
    endpoints:
      - &scpi_entity
        name: na_start_freq
        module: SimpleSCPIEntity
        base_str: :SENSe:FREQuency:STARt
        calibration: "{}"
      - <<: *scpi_entity
        name: na_stop_freq
        base_str: :SENSe:FREQuency:STOP
      - <<: *scpi_entity
        name: na_center_freq
        base_str: :SENSe:FREQuency:CENTer
      - <<: *scpi_entity
        name: na_freq_span
        base_str: :SENSe:FREQuency:SPAN
      - <<: *scpi_entity
        name: na_power
        base_str: :SOUR1:POW
      - <<: *scpi_entity
        name: na_averages
        base_str: :SENS:AVER:COUNT
      - <<: *scpi_entity
        name: na_average_enable
        base_str: :SENS:AVER:STAT
      - <<: *scpi_entity
        name: na_sweep_points
        base_str: :SENS1:SWE:POIN
      - <<: *scpi_entity
        name: na_if_band
        base_str: :SENS1:BAND:RES
      - name: na_trigger
        module: FormatEntity
        get_str: ":TRIG:SOUR BUS;:TRIG:SING;:STAT:OPER:COND?"
        calibration: '{}'
      - name: na_sweep_finished
        module: FormatEntity
        get_str: ":STAT:OPER:COND?"
        calibration: 'False if (int({}) &  0b10000) else True'
      - name: na_freq_data
        module: FormatEntity
        get_str: ":SENS1:FREQ:DATA?"
        calibration: "[{}]"
      - name: na_s21_iq_data
        module: FormatEntity
        get_str: ":CALC:PAR:DEF S21; :CALC1:DATA:SDAT?"
        calibration: "[{}]"
      - name: na_s11_iq_data
        module: FormatEntity
        get_str: ":CALC:PAR:DEF S11; :CALC1:DATA:SDAT?"
        calibration: "[{}]"

```

### NA log output
```
raphaelc@nlwymmd:~$ kubectl logs na-dripline-python-deployment-6b7c997f56-4k7bt
2020-05-14T15:31:05[INFO    ] dripline(86) -> python got a master config:
{'dripline': {'alerts-exchange': 'alerts', 'broker': 'rabbitmq-app.default.svc.cluster.local', 'heartbeat-interval-s': 60, 'heartbeat-routing-key': 'heartbeat', 'loop-timeout-ms': 1000, 'max-payload-size': 10000, 'message-wait-ms': 1000, 'requests-exchange': 'requests'}, 'runtime-config': {'auth_file': '/etc/rabbitmq-secret/authentications.json', 'cmd_at_reconnect': [None, 'SYST:ERRor?', '*OPC?'], 'command_terminator': '\n', 'endpoints': [{'base_str': ':SENSe:FREQuency:STARt', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_start_freq'}, {'base_str': ':SENSe:FREQuency:STOP', 'calibration': '{}', 'module': 'SimpleSCPIE
ntity', 'name': 'na_stop_freq'}, {'base_str': ':SENSe:FREQuency:CENTer', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_center_freq'}, {'base_str': ':SENSe:FREQuency:SPAN', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_freq_span'}, {'base_str': ':SOUR1:POW', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_power'}, {'base_str': ':SENS:AVER:COUNT', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_averages'}, {'base_str': ':SENS:AVER:STAT', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_average_enable'}, {'base_str': ':SENS1:SWE:POIN', 'calibration': '{}', 'm
odule': 'SimpleSCPIEntity', 'name': 'na_sweep_points'}, {'base_str': ':SENS1:BAND:RES', 'calibration': '{}', 'module': 'SimpleSCPIEntity', 'name': 'na_if_band'}, {'calibration': '{}', 'get_str': ':TRIG:SOUR BUS;:TRIG:SING;:STAT:OPER:COND?', 'module': 'FormatEntity', 'name': 'na_trigger'}, {'calibration': 'False if (int({}) &  0b10000) else True', 'get_str': ':STAT:OPER:COND?', 'module': 'FormatEntity', 'name': 'na_sweep_finished'}, {'calibration': '[{}]', 'get_str': ':SENS1:FREQ:DATA?', 'module': 'FormatEntity', 'name': 'na_freq_data'}, {'calibration': '[{}]', 'get_str': ':CALC:PAR:DEF S21; :CALC1:DATA:SDAT?', 'module': 'FormatEntit
y', 'name': 'na_s21_iq_data'}, {'calibration': '[{}]', 'get_str': ':CALC:PAR:DEF S11; :CALC1:DATA:SDAT?', 'module': 'FormatEntity', 'name': 'na_s11_iq_data'}], 'module': 'EthernetSCPIService', 'name': 'na', 'reconnect_test': '+1', 'response_terminator': '\n', 'socket_info': '("192.168.25.7",5025)', 'socket_timeout': 3}}
2020-05-14 15:31:05 [ PROG] i/application.cc(128): Final configuration:
{
    dripline :
    {
        alerts-exchange : alerts
        broker : rabbitmq-app.default.svc.cluster.local
        heartbeat-interval-s : 60
        heartbeat-routing-key : heartbeat
        loop-timeout-ms : 1000
        max-payload-size : 10000
        message-wait-ms : 1000
        requests-exchange : requests
    }
    runtime-config :
    {
        auth_file : /etc/rabbitmq-secret/authentications.json
        cmd_at_reconnect :
        [
            SYST:ERRor?
            *OPC?
        ]
        command_terminator :
        endpoints :
        [
            {
                base_str : :SENSe:FREQuency:STARt
                calibration : {}
                module : SimpleSCPIEntity
                name : na_start_freq
            }

            {
                base_str : :SENSe:FREQuency:STOP
                calibration : {}
                module : SimpleSCPIEntity
                name : na_stop_freq
            }

            {
                base_str : :SENSe:FREQuency:CENTer
                calibration : {}
                module : SimpleSCPIEntity
                name : na_center_freq
            }

            {
                base_str : :SENSe:FREQuency:SPAN
                calibration : {}
                module : SimpleSCPIEntity
                name : na_freq_span
            }

            {
                base_str : :SOUR1:POW
                calibration : {}
                module : SimpleSCPIEntity
                name : na_power
            }

            {
                base_str : :SENS:AVER:COUNT
                calibration : {}
                module : SimpleSCPIEntity
                name : na_averages
            }

            {
                base_str : :SENS:AVER:STAT
                calibration : {}
                module : SimpleSCPIEntity
                name : na_average_enable
            }

            {
                base_str : :SENS1:SWE:POIN
                calibration : {}
                module : SimpleSCPIEntity
                name : na_sweep_points
            }

            {
                base_str : :SENS1:BAND:RES
                calibration : {}
                module : SimpleSCPIEntity
                name : na_if_band
            }

            {
                calibration : {}
                get_str : :TRIG:SOUR BUS;:TRIG:SING;:STAT:OPER:COND?
                module : FormatEntity
                name : na_trigger
            }

            {
                calibration : False if (int({}) &  0b10000) else True
                get_str : :STAT:OPER:COND?
                module : FormatEntity
                name : na_sweep_finished
            }

            {
                calibration : [{}]
                get_str : :SENS1:FREQ:DATA?
                module : FormatEntity
                name : na_freq_data
            }

            {
                calibration : [{}]
                get_str : :CALC:PAR:DEF S21; :CALC1:DATA:SDAT?
                module : FormatEntity
                name : na_s21_iq_data
            }

            {
                calibration : [{}]
                get_str : :CALC:PAR:DEF S11; :CALC1:DATA:SDAT?
                module : FormatEntity
                name : na_s11_iq_data
            }
        ]
        module : EthernetSCPIService
        name : na
        reconnect_test : +1
        response_terminator :
        socket_info : ("192.168.25.7",5025)
        socket_timeout : 3
    }
}
2020-05-14 15:31:05 [ PROG] i/application.cc(129): Ordered args:
[
]
2020-05-14T15:31:08[WARNING ] dripline.implementations.ethernet_scpi_service(84) -> connection ('192.168.25.7', 5025) refused: timed out
2020-05-14T15:31:08[ERROR   ] dripline(75) -> got an error...
2020-05-14T15:31:08[ERROR   ] dripline(76) -> traceback was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dripline/implementations/ethernet_scpi_service.py", line 82, in _reconnect
    self.socket = socket.create_connection(self.socket_info, self.socket_timeout)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/dl-serve", line 73, in run
    self._run(the_app)
  File "/usr/local/bin/dl-serve", line 96, in _run
    the_service = self.create_object( run_config )
  File "/usr/local/bin/dl-serve", line 67, in create_object
    the_object = module( **a_config )
  File "/usr/local/lib/python3.7/site-packages/dripline/implementations/ethernet_scpi_service.py", line 72, in __init__
    self._reconnect()
  File "/usr/local/lib/python3.7/site-packages/dripline/implementations/ethernet_scpi_service.py", line 85, in _reconnect
    raise ThrowReply('resource_error_connection', f"Unable to establish ethernet socket {self.socket_info}")
dripline.core.throw_reply.ThrowReply: Unable to establish ethernet socket ('192.168.25.7', 5025)
```
